import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
public class USERMENU extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    Connection  conn =null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    ResultSet rs2=null;
    PreparedStatement pst2=null;
    
    public USERMENU() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("pics/logo3.png")).getImage());
    }
    
    public void tableResize(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15;
            for(int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width+1, width);
            }
            if(width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    
    
    
    void ProductTable()
    {
        String sql="select p_barcode AS 'Barcode', p_name AS 'Product name', p_brand AS 'Brand', p_weight AS 'Weight', c_stock AS 'Stock' from product where c_stock='0'";
        try{
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();
            productTable.setModel(DbUtils.resultSetToTableModel(rs));
            tableResize(productTable);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     public static String now() {
       String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss";

        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
        return sdf.format(cal.getTime());
    }
     
     public static String monthYear() {
        
    String DATE_FORMAT_NOW = "yyyy-MM";

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
    return sdf.format(cal.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        HOMEpanel = new javax.swing.JPanel();
        addProductBtn = new javax.swing.JLabel();
        inventoryBtn = new javax.swing.JLabel();
        reportBtn = new javax.swing.JLabel();
        topBrandChart = new javax.swing.JPanel();
        topProductChart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        logoutBtn = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        userbg = new javax.swing.JLabel();
        LOGOUTpanel = new javax.swing.JPanel();
        jYes = new javax.swing.JLabel();
        jNo = new javax.swing.JLabel();
        jQuestion = new javax.swing.JLabel();
        clr = new javax.swing.JLabel();
        homebg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 720));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1350, 720));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1350, 720));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HOMEpanel.setMaximumSize(new java.awt.Dimension(1350, 720));
        HOMEpanel.setMinimumSize(new java.awt.Dimension(1350, 720));
        HOMEpanel.setPreferredSize(new java.awt.Dimension(1350, 720));
        HOMEpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        addProductBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addProductBtn.setText("MANAGE PRODUCT");
        addProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductBtnMouseExited(evt);
            }
        });
        HOMEpanel.add(addProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 222, 239, 40));

        inventoryBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        inventoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryBtn.setText("INVENTORY");
        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseExited(evt);
            }
        });
        HOMEpanel.add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 306, 239, 40));

        reportBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        reportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportBtn.setText("REPORT");
        reportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportBtnMouseExited(evt);
            }
        });
        HOMEpanel.add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 390, 239, 40));

        javax.swing.GroupLayout topBrandChartLayout = new javax.swing.GroupLayout(topBrandChart);
        topBrandChart.setLayout(topBrandChartLayout);
        topBrandChartLayout.setHorizontalGroup(
            topBrandChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        topBrandChartLayout.setVerticalGroup(
            topBrandChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        HOMEpanel.add(topBrandChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 75, 440, 305));

        javax.swing.GroupLayout topProductChartLayout = new javax.swing.GroupLayout(topProductChart);
        topProductChart.setLayout(topProductChartLayout);
        topProductChartLayout.setHorizontalGroup(
            topProductChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        topProductChartLayout.setVerticalGroup(
            topProductChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        HOMEpanel.add(topProductChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 75, 440, 310));

        jScrollPane2.setBackground(new java.awt.Color(210, 156, 50));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        productTable = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        productTable.setBackground(new java.awt.Color(255, 102, 102));
        productTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        productTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        productTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(productTable);

        HOMEpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 390, 860, 314));

        logoutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("LOGOUT");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        HOMEpanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 80, 30));

        minimize.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("–");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        HOMEpanel.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 12, 20));

        userbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/stockin_UI.PNG"))); // NOI18N
        HOMEpanel.add(userbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        jLayeredPane1.add(HOMEpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        LOGOUTpanel.setMaximumSize(new java.awt.Dimension(1350, 720));
        LOGOUTpanel.setMinimumSize(new java.awt.Dimension(1350, 720));
        LOGOUTpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jYes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jYes.setText("YES");
        jYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jYesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jYesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jYesMouseExited(evt);
            }
        });
        LOGOUTpanel.add(jYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 390, 40, 20));

        jNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jNo.setText("NO");
        jNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNoMouseExited(evt);
            }
        });
        LOGOUTpanel.add(jNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 390, 30, 20));

        jQuestion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logout question.png"))); // NOI18N
        LOGOUTpanel.add(jQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 374, 211));

        clr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/clr.png"))); // NOI18N
        clr.setIconTextGap(0);
        clr.setMaximumSize(new java.awt.Dimension(1350, 710));
        clr.setMinimumSize(new java.awt.Dimension(1350, 710));
        clr.setPreferredSize(new java.awt.Dimension(1350, 710));
        LOGOUTpanel.add(clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 700));
        LOGOUTpanel.add(homebg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        jLayeredPane1.add(LOGOUTpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseClicked
        this.dispose();
        ADDPRODUCT a=new ADDPRODUCT();
        a.setVisible(true);
        
    }//GEN-LAST:event_addProductBtnMouseClicked

    private void inventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseClicked
       this.dispose();
        INVENTORY i=new INVENTORY();
        i.setVisible(true);
    }//GEN-LAST:event_inventoryBtnMouseClicked

    private void jYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jYesMouseClicked
        this.dispose();
        LOGIN login = new LOGIN();
        login.setVisible(true);
    }//GEN-LAST:event_jYesMouseClicked

    private void jNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoMouseClicked
        HOMEpanel.setVisible(true);
        LOGOUTpanel.setVisible(false);
    }//GEN-LAST:event_jNoMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        HOMEpanel.setVisible(false);
        LOGOUTpanel.setVisible(true);
        
        String stat = LOGIN.status;
        if(stat.equals("Stock-in user")) {
            homebg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/stockin_UI.PNG")));
        }
                
        else if(stat.equals("Stock-out user")) {
            addProductBtn.setVisible(false);
            homebg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/stockout_UI.PNG")));
        }
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void jYesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jYesMouseEntered
        jYes.setForeground(Color.white);
    }//GEN-LAST:event_jYesMouseEntered

    private void jNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoMouseEntered
        jNo.setForeground(Color.white);
    }//GEN-LAST:event_jNoMouseEntered

    private void jNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoMouseExited
        jNo.setForeground(Color.black);
    }//GEN-LAST:event_jNoMouseExited

    private void jYesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jYesMouseExited
       jYes.setForeground(Color.black);
    }//GEN-LAST:event_jYesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn=mysqlconnect.ConnectDb();
        
        ProductTable();
        tableResize(productTable);
        HOMEpanel.setVisible(true);
        LOGOUTpanel.setVisible(false);
        
        String stat = LOGIN.status;
        if(stat.equals("Stock-in user")) {
            userbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/stockin_UI.PNG")));
        }
                
        else if(stat.equals("Stock-out user")) {
            addProductBtn.setVisible(false);
            userbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/stockout_UI.PNG")));
        }
        
        //TOP BRAND this month
         
        String my= ""+ monthYear();
        String sql = "select p_brand AS 'Brand', SUM(qty_out) AS 'Quantity sold' from product JOIN released_by ON product.p_barcode=released_by.Rbarcode where date_out LIKE ? group by p_brand order by SUM(qty_out) DESC LIMIT 5";
        try{
            pst= conn.prepareStatement(sql);
            
            pst.setString(1, my + "%");
            rs=pst.executeQuery();
            
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        
       while(rs.next()){ 
           //JOptionPane.showMessageDialog(null, rs.getString(1));
        
        dataset.setValue(Float.parseFloat(rs.getString(2)),"Brand",(rs.getString(1)));
       }
        
       JFreeChart chart=ChartFactory.createBarChart3D("Top Brand This Month","Brand name","Quantity sold", dataset,PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.WHITE);
        CategoryPlot P=chart.getCategoryPlot();
        //P.setForegroundAlpha(TOP_ALIGNMENT);
        P.setRangeGridlinePaint(Color.BLACK);
        
        BarRenderer barRenderer = (BarRenderer)P.getRenderer(); 
        barRenderer.setSeriesPaint(0,new Color(0, 153, 153));topBrandChart.setLayout(new java.awt.BorderLayout());
        ChartPanel CP = new ChartPanel(chart);
        topBrandChart.add(CP,BorderLayout.CENTER);
        topBrandChart.validate();
        
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        //TOP PRODUCT this month
         
        String myy= ""+ monthYear();
        String sql2 = "select p_name AS 'Product name', SUM(qty_out) AS 'Quantity sold' from product JOIN released_by ON product.p_barcode=released_by.Rbarcode where date_out LIKE ? group by p_name order by SUM(qty_out) DESC LIMIT 5";
        try{
            pst2= conn.prepareStatement(sql2);
            
            pst2.setString(1, myy + "%");
                //pst2.setString(2, "%" + searchProduct.getText() + "%");
            rs2=pst2.executeQuery();
            
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        
       while(rs2.next()){ 
           //JOptionPane.showMessageDialog(null, rs.getString(1));
        
        dataset.setValue(Float.parseFloat(rs2.getString(2)),"Product",(rs2.getString(1)));
       }
        
       JFreeChart chart=ChartFactory.createBarChart3D("Top Product This Month","Product name","Quantity sold", dataset,PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.WHITE);
        CategoryPlot P=chart.getCategoryPlot();
        //P.setForegroundAlpha(TOP_ALIGNMENT);
        P.setRangeGridlinePaint(Color.BLACK);
        
        BarRenderer barRenderer = (BarRenderer)P.getRenderer(); 
        barRenderer.setSeriesPaint(0,new Color(144, 12, 63));topProductChart.setLayout(new java.awt.BorderLayout());
        ChartPanel CP = new ChartPanel(chart);
        topProductChart.add(CP,BorderLayout.CENTER);
        topProductChart.validate();
        
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void reportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseClicked
        this.dispose();
        REPORT r=new REPORT();
        r.setVisible(true);
    }//GEN-LAST:event_reportBtnMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(USERMENU.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setForeground(Color.decode("#d29c32"));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setForeground(Color. white);
    }//GEN-LAST:event_minimizeMouseExited

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setForeground(Color.decode("#d29c32"));
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        logoutBtn.setForeground(Color. white);
    }//GEN-LAST:event_logoutBtnMouseExited

    private void addProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseEntered
        addProductBtn.setForeground(Color. white);
    }//GEN-LAST:event_addProductBtnMouseEntered

    private void addProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseExited
        addProductBtn.setForeground(Color. black);
    }//GEN-LAST:event_addProductBtnMouseExited

    private void inventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseEntered
        inventoryBtn.setForeground(Color. white);
    }//GEN-LAST:event_inventoryBtnMouseEntered

    private void inventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseExited
        inventoryBtn.setForeground(Color. black);
    }//GEN-LAST:event_inventoryBtnMouseExited

    private void reportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseEntered
        reportBtn.setForeground(Color. white);
    }//GEN-LAST:event_reportBtnMouseEntered

    private void reportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseExited
        reportBtn.setForeground(Color. black);
    }//GEN-LAST:event_reportBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HOMEpanel;
    private javax.swing.JPanel LOGOUTpanel;
    private javax.swing.JLabel addProductBtn;
    private javax.swing.JLabel clr;
    private javax.swing.JLabel homebg1;
    private javax.swing.JLabel inventoryBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jNo;
    private javax.swing.JLabel jQuestion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jYes;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel minimize;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel reportBtn;
    private javax.swing.JPanel topBrandChart;
    private javax.swing.JPanel topProductChart;
    private javax.swing.JLabel userbg;
    // End of variables declaration//GEN-END:variables
}
